### ISSUE TITLE
faker-cli uuid help shows error

### ISSUE THREAD

**Issue by mkelley33** [lestoni/faker-cli#3]
To reproduce issue install node v6.0.0, nvm, and faker-cli, then issue the following command: 

`faker-cli uuid help`

Maybe an update to the README for node version compatibility would be helpful :)

```
Available options for undefined:
/Users/user.name/.nvm/versions/node/v6.0.0/lib/node_modules/faker-cli/index.js:207
  return Object.keys(faker[which]);
                ^

TypeError: Cannot convert undefined or null to object
    at module.exports.fields (/Users/user.name/.nvm/versions/node/v6.0.0/lib/node_modules/faker-cli/index.js:207:17)
    at printHelp (/Users/user.name/.nvm/versions/node/v6.0.0/lib/node_modules/faker-cli/bin/faker-cli.js:172:3)
    at print (/Users/user.name/.nvm/versions/node/v6.0.0/lib/node_modules/faker-cli/bin/faker-cli.js:182:9)
    at Object.<anonymous> (/Users/user.name/.nvm/versions/node/v6.0.0/lib/node_modules/faker-cli/bin/faker-cli.js:48:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)

```

**Comment by lestoni** [comment]
@deanrad Sorry i haven't been paying much attention to this for some time (if not years :D ) , been on other things ! i'll check it out and if you can offer any contribution feel free : )
