### ISSUE TITLE
Not able to set locale

### ISSUE THREAD

**Issue by KevCui** [lestoni/faker-cli#5]
~$ faker-cli -L help                                                                                     
     Available options for undefined:
/usr/lib/node_modules/faker-cli/index.js:207
  return Object.keys(faker[which]);
                ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at module.exports.fields (/usr/lib/node_modules/faker-cli/index.js:207:17)
    at printHelp (/usr/lib/node_modules/faker-cli/bin/faker-cli.js:172:3)
    at print (/usr/lib/node_modules/faker-cli/bin/faker-cli.js:182:9)
    at Object.<anonymous> (/usr/lib/node_modules/faker-cli/bin/faker-cli.js:48:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by KevCui** [comment]
Didn't notice the usage in Example, sorry my bad. It works without problem:
~$ faker-cli -L fr -n firstName
